# Generated by Django 3.0.8 on 2020-08-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='', max_length=20, null=True)),
                ('Lastname', models.CharField(default='', max_length=20, null=True)),
                ('Img', models.ImageField(blank=True, upload_to='')),
                ('Date_Of_Birth', models.DateField(null=True)),
                ('Email', models.EmailField(default='', max_length=254, null=True)),
                ('Course', models.TextField(default='', null=True)),
                ('Branch', models.TextField(default='', null=True)),
                ('Section', models.TextField(default='', null=True)),
                ('Enrollment_no', models.TextField(default='', max_length=20, null=True)),
                ('Scholar_no', models.IntegerField(default='', null=True)),
                ('Year', models.TextField(default='', null=True)),
                ('Address', models.TextField(default='', null=True)),
                ('City', models.TextField(default='', null=True)),
                ('State', models.TextField(default='', null=True)),
                ('Mobile_no', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email_From_Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, default='', max_length=254)),
                ('Subject', models.TextField(blank=True, default='')),
                ('Message', models.TextField(blank=True, default='')),
                ('Date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email_To_Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, upload_to='media/Email/images')),
                ('Subject', models.TextField(blank=True, default='')),
                ('Message', models.TextField(blank=True, default='')),
                ('File', models.FileField(blank=True, upload_to='Email/files')),
                ('Date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/Events')),
                ('Name', models.CharField(blank=True, default='', max_length=25)),
                ('Description', models.TextField(blank=True, default='')),
                ('Venue', models.TextField(blank=True, default='')),
                ('Time', models.TimeField(blank=True)),
                ('Date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, default='', max_length=254)),
                ('Feedback', models.TextField(blank=True, default='')),
                ('Date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Image', models.ImageField(upload_to='media/Jobs')),
                ('Company_Name', models.CharField(blank=True, default='', max_length=50)),
                ('Job_Title', models.CharField(blank=True, default='', max_length=50)),
                ('Job_Prerequisite', models.TextField(blank=True, default='')),
                ('Job_Description', models.TextField(blank=True, default='')),
                ('Company_Info', models.TextField(blank=True, default='')),
                ('location', models.TextField(blank=True, default='')),
                ('Apply_Process', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, default='', max_length=50)),
                ('Description', models.TextField(blank=True, default='')),
                ('IssueDate', models.DateField(null=True)),
            ],
        ),
    ]
