# Generated by Django 2.2.6 on 2020-06-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_To_Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/Emails/Images')),
                ('Subject', models.TextField(blank=True, default='')),
                ('Message', models.TextField(blank=True, default='')),
                ('File', models.FileField(upload_to='media/Emails/Files')),
                ('Date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/Events')),
                ('EventName', models.TextField(blank=True, default='')),
                ('Description', models.TextField(blank=True, default='')),
                ('EventDate', models.DateField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.AddField(
            model_name='alumni',
            name='Date_joined',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumni',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='email_from_alumni',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='EventDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='IssueDate',
            field=models.DateField(null=True),
        ),
    ]
