# Generated by Django 3.0.8 on 2020-08-01 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email_To_Alumni',
        ),
    ]
