# Generated by Django 3.0.7 on 2020-06-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='Img',
            field=models.ImageField(blank=True, upload_to='Alumni'),
        ),
        migrations.AlterField(
            model_name='email_to_alumni',
            name='File',
            field=models.FileField(upload_to='Emails/Files'),
        ),
        migrations.AlterField(
            model_name='email_to_alumni',
            name='Image',
            field=models.ImageField(upload_to='Emails/Images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Image',
            field=models.ImageField(upload_to='Events'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Image',
            field=models.ImageField(upload_to='Gallery'),
        ),
        migrations.AlterField(
            model_name='job',
            name='Company_Image',
            field=models.ImageField(upload_to='Jobs'),
        ),
    ]
