# Generated by Django 3.0.8 on 2020-09-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Company_Info',
            new_name='Experience',
        ),
        migrations.AddField(
            model_name='job',
            name='Salary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
