# Generated by Django 3.0.8 on 2020-08-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_management', '0002_delete_email_to_alumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.TextField(blank=True, default=''),
        ),
    ]
