# Generated by Django 2.2.6 on 2020-06-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_management', '0002_auto_20200613_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='username',
            field=models.CharField( max_length=10, null=True, unique=True),
        ),
    ]
