# Generated by Django 3.0.8 on 2020-09-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Management', '0002_auto_20200903_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_from_alumni',
            name='User_id',
            field=models.IntegerField(null=True),
        ),
    ]
