# Generated by Django 3.0.7 on 2020-06-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_management', '0002_auto_20200620_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='Date_Of_Birth',
            field=models.DateField(null=True),
        ),
    ]
