# Generated by Django 3.0.8 on 2020-09-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_Management', '0003_email_from_alumni_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='User_id',
            field=models.IntegerField(null=True),
        ),
    ]
